version: '3.8'

services:
  app:
    container_name: geo_preprocessing_module
    build: ./
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FASTAPI_HOST=localhost
      - FASTAPI_PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=geo_preprocessing_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bus-geo-preprocessing-db
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PROCESS_POOL_WORKERS_NUM=8
    ports:
      - ${FASTAPI_PORT}:8000
    volumes:
      - ./app:/src/app
    networks:
      - net
    command: bash -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0'
    restart: always

  db:
    container_name: geo_preprocessing_db
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=geo_preprocessing_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bus-geo-preprocessing-db
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgres/data
    networks:
      - net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 5
    restart: always

  vis-tool:
    container_name: geo-preprocessing-visualization-tool
    build: ./visualization_tool
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - app
    restart: always

volumes:
  db_volume:

networks:
  net:
    driver: bridge